"""
End-to-end regression test for Future.on_done() callbacks.

This test is SELF-CONTAINED: it drives the full Ventis stack the same way a
real user would, then asserts that callbacks fired correctly.

    scaffold (ventis new-project)
      -> swap in a callback-exercising workflow
      -> ventis build         (stubs + protos + Docker images)
      -> ventis deploy         (Redis + agent + workflow containers, gRPC)
      -> POST /main            (runs the workflow)
      -> GET /status/<id>      (reads the callback observations)
      -> assert
      -> tear down             (kill deploy, remove containers)

Unlike test_integration.py (which polls an already-deployed instance), this
script owns the whole lifecycle so it can be run standalone:

    python tests/test_callback_e2e.py

Requirements:
    - Docker running (Colima or Docker Desktop).
    - The ventis package installed in the current interpreter (pip install -e .).

Exit code 0 on success, non-zero on any failure.
"""

import json
import os
import shutil
import signal
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request

API = "http://localhost:8080"
VENTIS = [sys.executable, "-m", "ventis.cli"]

# Workflow that exercises the three on_done() behaviors through the full stack.
CALLBACK_WORKFLOW = '''\
# Auto-generated by tests/test_callback_e2e.py — exercises Future.on_done().
import sys, os, time, threading

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "stubs"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "grpc_stubs"))

from deploy import deploy
from example_agent_stub import ExampleAgentStub


def main(name: str = "World"):
    agent = ExampleAgentStub()

    # 1. Deferred fire: register before the result is ready -> watcher thread fires it.
    f1 = agent.hello(name=name)
    box = {}
    ev = threading.Event()

    def cb_deferred(result):
        box["deferred_result"] = result
        box["deferred_fired"] = True
        ev.set()

    f1.on_done(cb_deferred)
    deferred_in_time = ev.wait(timeout=30)

    # 2. Immediate fire: register after .value() cached the result -> fires synchronously.
    f2 = agent.hello(name="Immediate")
    f2.value()
    box2 = {}

    def cb_immediate(result):
        box2["immediate_result"] = result
        box2["immediate_fired"] = True

    f2.on_done(cb_immediate)

    # 3. Multiple callbacks fire in registration order.
    f3 = agent.hello(name="Multi")
    order = []
    f3.on_done(lambda r: order.append("A"))
    f3.on_done(lambda r: order.append("B"))
    f3.value()
    time.sleep(0.3)

    return {
        "deferred_fired": box.get("deferred_fired", False),
        "deferred_result": box.get("deferred_result"),
        "deferred_in_time": deferred_in_time,
        "immediate_fired": box2.get("immediate_fired", False),
        "immediate_result": box2.get("immediate_result"),
        "callback_order": order,
    }


deploy(main, port=8080)
'''

# Minimal config: only ExampleAgent + Workflow (no GPU-requesting VllmAgent).
MINIMAL_CONFIG = """\
agents:
  - name: ExampleAgent
    host: localhost
    port: 8051
    redis_port: 6379
    replicas: 1
    resources:
      cpu: 1
      memory: 512
    entrypoint: agents/example_agent.py

  - name: Workflow
    host: localhost
    port: 8050
    type: workflow
    api_port: 8080
    redis_port: 6379
    replicas: 1
    workflow_file: workflows/example_workflow.py

poll_interval: 5
redis:
  host: localhost
  port: 6379
  db: 0
"""

CONTAINERS = ["ventis-workflow-0", "ventis-exampleagent-0", "ventis-redis-localhost"]


def _run(cmd, cwd=None):
    """Run a command, streaming nothing, raising on failure."""
    print(f">> {' '.join(cmd)}  (cwd={cwd or os.getcwd()})")
    subprocess.run(cmd, cwd=cwd, check=True)


def _docker_ok():
    try:
        subprocess.run(["docker", "info"], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except Exception:
        return False


def _teardown(deploy_proc):
    print(">> Tearing down...")
    if deploy_proc and deploy_proc.poll() is None:
        deploy_proc.send_signal(signal.SIGTERM)  # triggers GlobalController.cleanup()
        try:
            deploy_proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            deploy_proc.kill()
    # Belt-and-suspenders: remove any containers the cleanup missed.
    subprocess.run(["docker", "rm", "-f", *CONTAINERS],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def _wait_for_api(timeout=90):
    """Poll POST /main until the workflow API answers (HTTP 202)."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            req = urllib.request.Request(
                f"{API}/main", data=b"{}",
                headers={"Content-Type": "application/json"}, method="POST")
            with urllib.request.urlopen(req, timeout=3) as r:
                if r.status == 202:
                    return True
        except Exception:
            pass
        time.sleep(2)
    return False


def _post_main(name):
    req = urllib.request.Request(
        f"{API}/main", data=json.dumps({"name": name}).encode(),
        headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=5) as r:
        return json.load(r)["request_id"]


def _poll_status(request_id, timeout=45):
    deadline = time.time() + timeout
    while time.time() < deadline:
        with urllib.request.urlopen(f"{API}/status/{request_id}", timeout=5) as r:
            data = json.load(r)
        if data.get("status") in ("done", "error"):
            return data
        time.sleep(1)
    raise TimeoutError(f"Workflow {request_id} did not finish within {timeout}s")


def _assert_callbacks(result):
    """Validate the callback observations returned by the workflow."""
    checks = [
        ("deferred_fired is True", result.get("deferred_fired") is True),
        ("deferred_in_time is True", result.get("deferred_in_time") is True),
        ("deferred_result correct",
         result.get("deferred_result") == "Hello, CallbackTest! I'm the ExampleAgent."),
        ("immediate_fired is True", result.get("immediate_fired") is True),
        ("immediate_result correct",
         result.get("immediate_result") == "Hello, Immediate! I'm the ExampleAgent."),
        ("callbacks fired in order", result.get("callback_order") == ["A", "B"]),
    ]
    failures = [name for name, ok in checks if not ok]
    for name, ok in checks:
        print(f"   [{'PASS' if ok else 'FAIL'}] {name}")
    if failures:
        raise AssertionError(f"{len(failures)} callback check(s) failed: {failures}")


def main():
    if not _docker_ok():
        print("SKIP: Docker is not available/running.")
        return 0

    workdir = tempfile.mkdtemp(prefix="ventis_cb_e2e_")
    project = os.path.join(workdir, "cb_e2e")
    deploy_proc = None
    try:
        # 1. Scaffold
        _run(VENTIS + ["new-project", "cb_e2e"], cwd=workdir)

        # 2. Swap in the callback workflow + minimal config
        with open(os.path.join(project, "workflows", "example_workflow.py"), "w") as f:
            f.write(CALLBACK_WORKFLOW)
        with open(os.path.join(project, "config", "global_controller.yaml"), "w") as f:
            f.write(MINIMAL_CONFIG)

        # 3. Build
        _run(VENTIS + ["build"], cwd=project)

        # 4. Deploy (background)
        print(">> ventis deploy (background)")
        deploy_proc = subprocess.Popen(
            VENTIS + ["deploy"], cwd=project,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        if not _wait_for_api():
            raise RuntimeError("Workflow API never came up on :8080")
        print(">> API is up.")

        # 5. Fire the request + read callback observations
        rid = _post_main("CallbackTest")
        print(f">> request_id = {rid}")
        data = _poll_status(rid)
        if data["status"] != "done":
            raise AssertionError(f"Workflow errored: {data}")

        print(">> Workflow result:")
        print(json.dumps(data["result"], indent=2))

        # 6. Assert
        _assert_callbacks(data["result"])
        print("\nPASS: Future.on_done() callbacks verified end-to-end.")
        return 0

    except Exception as e:
        print(f"\nFAIL: {e}")
        return 1
    finally:
        _teardown(deploy_proc)
        shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
