name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Run Ruff: Lint"
        run: uvx ruff check .

      - name: "Run Ruff: Format Check"
        run: uvx ruff format --check .
      
      - name: "Install dependencies for Ty"
        run: |
            uv venv 
            uv pip install -e .
      
      - name: "Run Ty: Type Check"
        run: uvx ty check

# If you want to run this locally, install act and run "act pull_request"
# For fixing Ruff lint errors: uvx ruff check --fix .
# For fixing Ruff formatting errors: uvx ruff format .